version: '3.8'
services:
  node:
    image: node:latest
    command: bash -c "npm install && npm start"
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - SHEETS_API=$SHEETS_API
    ports:
      - "3000:3000"